[package]
name = "first_package"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
#Iota = { local = "../../iota/crates/iota-framework/packages/iota-framework"}
Iota = { local = "../../iota/crates/iota-framework/packages/iota-framework"}

[addresses]
ctf =  "0x0"
iota =  "0000000000000000000000000000000000000000000000000000000000000002"